ENGINE: Applyed patch from sci2tech - Must be checked since applyed manually due to the following:
nuxwin@mdev:~/Bureau/i-MSCP-WORKSPACE/imscp$ git apply --stat ../../patch/pacth.diff
 engine/PerlLib/Servers/named/bind.pm           |    2 ++
 engine/PerlLib/Servers/named/bind/installer.pm |   10 ++++++++--
 2 files changed, 10 insertions(+), 2 deletions(-)
nuxwin@mdev:~/Bureau/i-MSCP-WORKSPACE/imscp$ git apply --check ../../patch/pacth.diff
error: patch failed: engine/PerlLib/Servers/named/bind.pm:623
error: engine/PerlLib/Servers/named/bind.pm: patch does not apply
error: patch failed: engine/PerlLib/Servers/named/bind/installer.pm:152
error: engine/PerlLib/Servers/named/bind/installer.pm: patch does not apply
nuxwin@mdev:~/Bureau/i-MSCP-WORKSPACE/imscp$ mv ../../patch/pacth.diff ../../patch/patch.diff
nuxwin@mdev:~/Bureau/i-MSCP-WORKSPACE/imscp$ mv ../../patch/patch.diff ../../patch/patch.diff
mv: « ../../patch/patch.diff » et « ../../patch/patch.diff » identifient le même fichier
nuxwin@mdev:~/Bureau/i-MSCP-WORKSPACE/imscp$

Cause: local repository not synced before creating patch.